### ISSUE TITLE
Error while using libmagic

### ISSUE THREAD

**Issue by varayush007** [codebasics/langchain#9]
As you have taught in the lec I have Installed all the requirements related to Rocky Bot 

But still getting error
Code - 

from langchain.document_loaders import UnstructuredURLLoader

urls = [
        "https://www.moneycontrol.com/news/business/budget/fm-sitharaman-fixes-fy25-fiscal-deficit-target-at-5-1-of-gdp-12131621.html?pitchclick=TopNews",
        "https://www.moneycontrol.com/news/business/budget/fm-sitharaman-sets-fy25-capex-target-at-rs-11-1-lakh-crore-in-budget-12135441.html?pitchclick=Liveblog"
    ]

loader = UnstructuredURLLoader(urls=urls)

data = loader.load()
len(data)

Error -

libmagic is unavailable but assists in filetype detection on file-like objects. Please consider installing libmagic for better results.
Error fetching or processing https://www.moneycontrol.com/news/business/budget/fm-sitharaman-fixes-fy25-fiscal-deficit-target-at-5-1-of-gdp-12131621.html?pitchclick=TopNews, exception: Invalid file. The FileType.UNK file type is not supported in partition.
libmagic is unavailable but assists in filetype detection on file-like objects. Please consider installing libmagic for better results.
Error fetching or processing https://www.moneycontrol.com/news/business/budget/fm-sitharaman-sets-fy25-capex-target-at-rs-11-1-lakh-crore-in-budget-12135441.html?pitchclick=Liveblog, exception: Invalid file. The FileType.UNK file type is not supported in partition.

**Comment by shikhar2402** [comment]
Use this command pip3 install unstructured libmagic, it works for me
